# Generated by Django 3.1.5 on 2021-01-29 16:25

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.unique_code_generator, max_length=8, unique=True)),
                ('host_name', models.CharField(max_length=30, unique=True)),
                ('guest_can_pause', models.BooleanField(default=False)),
                ('votes_to_skip', models.IntegerField(default=2)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
