# Generated by Django 3.1.5 on 2021-01-31 16:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.code_creator, max_length=9, unique=True),
        ),
    ]
